language: node_js
node_js:
  - "6"
before_script:
  - npm install -g firebase-tools
  - npm install -g @angular/cli
script:
  - cd travistestapp
  - ng build --prod
after_success:
  - firebase deploy --token=${FIREBASE_TOKEN}
