language: node_js
node_js:
  - "6"
before_script:
  - ls
  - npm install -g firebase-tools
  - cd public
  - npm install -g @angular/cli
  - npm install
  - cd travistestapp
script:
  - ng build --prod
after_success:
  - firebase deploy --token=${FIREBASE_TOKEN}
