language: node_js
2 node_js:
3   - "0.10"
4 script:
5   - echo 'Hello Firebase'
6 install:
7   - npm install -g firebase-tools
8 after_success:
9   - firebase deploy --email ${USERNAME} --password ${PASSWORD}
